export type Movie = {
	adult: boolean;
	backdrop_path: string;
	budget: number;
	genres: { id: number; name: string }[];
	id: number;
	original_country: string[];
	original_language: string;
	original_title: string;
	overview: string;
	popularity: number;
	poster_path: string;
	release_date: Date;
	title: string;
	video: boolean;
	vote_average: number;
	vote_count: number;
	runtime: number;
	tagline: string;
	status: string;
};
